dist: bionic
os: linux
language: cpp
compiler:
  - gcc
  - clang

# Always test things that aren't pushes (like PRs)
# or test master or test tagged releases on push (with versioning)
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
    fast_finish: true

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - GTEST_COLOR=1 ctest --verbose
