name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Tools (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake

        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          brew install gcc
        fi

    - name: Set Environment
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "::set-env name=CC::gcc"
          echo "::set-env name=CXX::g++"
        else
          echo "::set-env name=CC::clang"
          echo "::set-env name=CXX::clang++"
        fi

    - name: Checkout Submodules
      run: |
        git submodule update --init --recursive --recommend-shallow

    - name: Build and Test
      run: |
        cmake -S . -B build-cmake
        cmake --build build-cmake
        cd build-cmake && GTEST_COLOR=1 ctest --verbose

